# -*- coding: utf-8 -*-
"""Descriptive Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpvjJzLQjIjVrbOL8auUtQVVAPyakYRe

# Measures of Central Tendency: Mean, Median and Mode
## Calculating Mean
## Method 1 - Manual Calculation
"""

## Preparing DataSet
Population = [150, 160, 170, 187, 150]
Sample = [150, 170, 187]

Pop_mean = sum(Population)/len(Population)
Sample_mean = sum(Sample)/len(Sample)

print("The Mean of Population is: ", Pop_mean)
print("The Mean of Sample is: ", Sample_mean)

"""## Method 2 - Using Numpy Library"""

## Importing Libraries
import numpy as np

## Preparing DataSet
Population = [150, 160, 170, 187, 150]
Sample = [150, 170, 187]

## Calculating Mean
Pop_mean = np.mean(Population)
Sample_mean = np.mean(Sample)

print("The Mean of Population is: ", Pop_mean)
print("The Mean of Sample is: ", Sample_mean)

"""## Method 3 - Using Statistics Library"""

## Importing Libraries
import statistics as stats

## Preparing DataSet
Population = [150, 160, 170, 187, 150]
Sample = [150, 170, 187]

## Calculating Mean
Pop_mean = stats.mean(Population)
Sample_mean = stats.mean(Sample)

print("The Mean of Population is: ", Pop_mean)
print("The Mean of Sample is: ", Sample_mean)

"""## Using Dataset - iris"""

# Commented out IPython magic to ensure Python compatibility.
## installing library seaborn
# %pip install seaborn

## importing library seaborn
import seaborn as sns

## using dataset predefined in library - iris dataset
## load dataset
iris_df = sns.load_dataset('iris')

## printing top 5 rows
print(iris_df.head())

print("___________________________________________________________________")

## Calculating mean of sepal_length
Sepal_length_mean = iris_df['sepal_length'].mean()
print("The mean of sepal length is: ", Sepal_length_mean)

Sepal_mean = np.mean(iris_df['sepal_length'])
print("The mean is: ", Sepal_mean)

"""# Calculating Median
### Method 1 - Using Numpy
"""

## Preparing DataSet
Dataset_values = [150, 160, 170, 187, 150]

## Calculating median
Data_median = np.median(Dataset_values)
print("The median of Data is: ", Data_median)

"""# Calculating Median
### Method 2 - Using Statistics
"""

import statistics as stats
## Preparing DataSet
Dataset_values = [150, 160, 170, 187, 150]

## Calculating median
Data_median = stats.median(Dataset_values)
print("The median of Data is: ", Data_median)

"""# Calculating Median
### Method 3 - Using PANDAS Library
"""

## importing library
import pandas as pd

## Preparing DataSet

Dataset_values = pd.DataFrame({
    'Values' : [150, 160, 170, 187, 150]
})

print(Dataset_values)

## Calculating median
Data_median = Dataset_values['Values'].median()
print("\nThe median of Data is: ", Data_median)

"""## Using Dataset"""

## importing library seaborn
import seaborn as sns

## using dataset predefined in library - iris dataset
## load dataset
iris_df = sns.load_dataset('iris')

## printing top 5 rows
print(iris_df.head())

print("___________________________________________________________________")

## Calculating mean of sepal_length
Sepal_length_median = iris_df['sepal_length'].median()
print("The median of sepal length is: ", Sepal_length_median)

Sepal_median = np.median(iris_df['sepal_length'])
print("The median is: ", Sepal_median)

"""# Calculating Mode
### Method 1 - Using Statistics Library
"""

## Importing Library
import statistics as stats

## Preparing Dataset
Data = [10, 20, 30, 20, 30, 40, 50, 50, 50, 50, 20, 20, 20, 50]

## Calculating Mode calling .mode function()
Data_Mode = stats.mode(Data)
print("The Mode of the Data is: ", Data_Mode)

## If there are multiple modes, then use multimode() function
Data_All_Mode = stats.multimode(Data)
print("All the Modes of the Data is: ", Data_All_Mode)

"""### Method 2 - Using Scipy Library"""

## Importing Library
from scipy import stats

## Preparing Dataset
Data = [10, 20, 30, 20, 30, 40, 50, 50, 50, 50, 20, 20, 20, 50]

## Calculating Mode calling .mode function()
Data_Mode = stats.mode(Data)
print("The Mode of the Data is: ", Data_Mode[0])

"""# Measures of Variability

### Calculating Variance

### Method 1 - Using Numpy Library


"""

## importing numpy library
import numpy as np

## Preparing Dataset
Data = [150, 160, 170, 187, 165]

## Calculating Variance for Population
Data_variance = np.var(Data, ddof = 0)
print("The Variance of the Population is: ", Data_variance)

## Calculating Variance for Sample
Sample_Variance = np.var(Data, ddof = 1)
print("The Variance of the Sample is: ", Sample_Variance)

"""## Method 2 - Using PANDAS Library

> Add blockquote


"""

## importing library
import pandas as pd

## Preparing DataSet
Dataset_values = [2,5,6,7,6,67,8,4,5,4,9,14,2,10]
Dataset_series = pd.Series(Dataset_values)

print(Dataset_series)

## Calculating Variance
## Note: By default, calculate Sample Variance
Sample_Data_variance = Dataset_series.var()
print("\nThe variance of Sample Data is: ", Sample_Data_variance)

## Calculating Variance of Population
Pop_Data_variance = Dataset_series.var(ddof = 0)
print("The variance of Population Data is: ", Pop_Data_variance)

"""## Method 3 - Using Scipy Library"""

## Importing Library
from scipy import stats

## Preparing Dataset
Data = [2,5,6,7,6,67,8,4,5,4,9,14,2,10]

## Calculating Variance calling .tvar function() - Sample Variance
Data_Variance = stats.tvar(Data)
print("The Variance of the Sample Data is: ", Data_Variance)

## Calculating Variance calling .tvar function(ddof = 0) - Population Variance
Data_Variance_Pop = stats.tvar(Data, ddof = 0)
print("The Variance of the Population Data is: ", Data_Variance_Pop)

"""## Calculating Standard Deviations
## Method 1 - Using Numpy Library
"""

## importing numpy library
import numpy as np

## Preparing Dataset
Data = [2,5,6,7,6,67,8,4,5,4,9,14,2,10]

## Calculating Standard Deviation for Population
Data_Pop_Std = np.std(Data, ddof = 0)
print("The Standard Deviation of the Population is: ", Data_Pop_Std)

## Calculating Standard Deviation for Sample
Sample_Std = np.std(Data, ddof = 1)
print("The Standard Deviation of the Sample is: ", Sample_Std)

"""## Method 2 - Using PANDAS Library"""

## importing library
import pandas as pd

## Preparing DataSet
Dataset_values = [2,5,6,7,6,67,8,4,5,4,9,14,2,10]
Dataset_series = pd.Series(Dataset_values)

print(Dataset_series)

## Calculating Standard Deviation
## Note: By default, calculate Sample STD
Sample_Data_STD = Dataset_series.std()
print("\nThe Standard Deviation of Sample Data is: ", Sample_Data_STD)

## Calculating Standard Deviation of Population
Pop_Data_STD = Dataset_series.std(ddof = 0)
print("The Standard Deviation of Population Data is: ", Pop_Data_STD)

"""## Method 3 - Using Scipy Library"""

## Importing Library
from scipy import stats
import math
## Preparing Dataset
Data = [2,5,6,7,6,67,8,4,5,4,9,14,2,10]

## Calculating STD calling .tvar function() - Sample STD
Data_STD = math.sqrt(stats.tvar(Data))
print("The STD of the Sample Data is: ", Data_STD)

## Calculating STD calling .tvar function(ddof = 0) - Population STD
Data_STD_Pop = math.sqrt(stats.tvar(Data, ddof = 0))
print("The STD of the Population Data is: ", Data_STD_Pop)

"""# Data Distribution
#### **Normal Distribution**

This distribution looks like a bell-shaped distribution.

**Note: Mean = Mode = Median - > Centre of the Bell**

Data is equally distributed before and after that line of mean, Median and Mode.

**NOTE:** As per the empirical rule in Normal Distribution -
1) 68.27% of the complete Population lies between (Mean - STD) & (Mean + STD)
2) 95.45% of the complete Population lies between (Mean - 2*STD) & (Mean + 2*STD)
3) 99.73% of the complete Population lies between (Mean - 3*STD) & (Mean + 3*STD)


### Standard Normal Distribution
Normal Distribution is converted into Standard Normal Distribution if:
##### Mean = 0
##### STD = 1


### Uniform Distribution
When the Probability of occurance of all the values are equal.
##### Graphs are straight Horizontal Line.

Mean = (a + b) / 2

STD = SQRT((b-a)^2/12)

"""

## Data Representation using Graphs
## Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew

#####################################################################################################################################

## Create a Figure and Axis,
fig, axs = plt.subplots(3, 2, figsize = (10, 8))
fig.suptitle('Histograms with KDE of various distributions', fontsize = 16)

## Normal Distribution
data_normal = np.random.normal(loc=50, scale = 10, size = 10000) # Mean = 50, STD = 10
sns.histplot(data_normal, kde = True, ax = axs[0,0], color = 'Black', stat = 'density', bins = 30)
axs[0,0].set_title('Normal Distribution')
axs[0,0].grid(True)

########################################################################################################################################
## Left-Right Skewed Distribution
data_right_skewed = np.random.exponential(scale = 10, size = 10000)  # right skewed
data_left_skewed = -np.random.exponential(scale = 10, size = 10000)   # left skewed

## Right Skewed Histogram
sns.histplot(data_right_skewed, kde = True, ax = axs[0,1], color = 'Blue', stat = 'density', bins = 30, label = 'Right_Skewed')
axs[0,1].set_title('Left_Right Skewed Histogram')
axs[0,1].grid(True)
axs[0,1].legend()

## Left Skewed Histogram
sns.histplot(data_left_skewed, kde = True, ax = axs[0,1], color = 'red', stat = 'density', bins = 30, label = 'Left_Skewed')
axs[0,1].set_title('Left_Right Skewed Histogram')
axs[0,1].grid(True)
axs[0,1].legend()

###############################################################################################################################
# --- 1. Right-Skewed Data (Positive Skew) ---
# Generate right-skewed data (e.g., income distribution or exponential data)
# np.random.exponential typically produces right-skewed data

data_right_skew = np.random.exponential(scale=2, size=10000) * 100

# Calculate statistics
mean_right = np.mean(data_right_skew)
median_right = np.median(data_right_skew)
skewness_right = skew(data_right_skew)

## Plotting of the Right_Skewed Histogram
sns.histplot(data_right_skewed, ax = axs[1,0], bins=30, kde=True, color='skyblue')
axs[1,0].set_title('Right Skewed Histogram')
axs[1,0].grid(True)

##########################################################################################################################
# --- 2. Left-Skewed Data (Negative Skew) ---
# Generate left-skewed data (e.g., test scores, if most people score high)
# A common technique is to subtract right-skewed data from a constant

data_left_skewed = 100 - np.random.exponential(scale=2, size=10000)
# Ensure no values exceed a reasonable upper bound for this example
data_left_skewed = np.clip(data_left_skewed, 0, 100)

# Calculate statistics
mean_left = np.mean(data_left_skewed)
median_left = np.median(data_left_skewed)
skewness_left = skew(data_left_skewed)

## Plotting of the Right_Skewed Histogram
sns.histplot(data_left_skewed, ax = axs[1,1], bins=30, kde=True, color='salmon')
axs[1,1].set_title('Left Skewed Histogram')
axs[1,1].grid(True)

############################################################################################################################

## Uniform Distribution
# --- 1. Generate Uniform Random Data using NumPy's Generator class (recommended) ---
# NumPy recommends using the default_rng() method for better randomness
data_uniform = np.random.uniform(low = 0, high = 10, size = 10000) # Uniform Distribution between 0 and 10
sns.histplot(data_uniform, ax = axs[2,0], color = 'green', stat = 'density', bins = 40, label = 'uniform samples')
axs[2,0].set_title('Uniform Distribution')
axs[2,0].grid(True)
axs[2,0].legend()

# --- 3. (Optional) Overlay the Theoretical PDF ---
# The PDF for a uniform distribution is a constant 1/(b-a)
high_bound = 10
low_bound = 0
pdf_value = 1 / (high_bound - low_bound)

# Create x values for the theoretical line
x = np.linspace(low_bound, high_bound, 100)

# Plot the theoretical PDF as a red line
axs[2,0].plot(x, [pdf_value] * len(x), 'r-', lw=2, label='Theoretical PDF')
axs[2,0].legend()

##########################################################################################################################

## Hiding and adjust subplot
axs[2,1].axis('off')

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew
import statistics as stats
import seaborn as sns

# Set a consistent style for the plots
sns.set_style("whitegrid")

# --- 1. Right-Skewed Data (Positive Skew) ---
# Generate right-skewed data (e.g., income distribution or exponential data)
# np.random.exponential typically produces right-skewed data
data_right_skewed = np.random.exponential(scale=2, size=1000) * 100

# Calculate statistics
mean_right = np.mean(data_right_skewed)
median_right = np.median(data_right_skewed)
mode_right = stats.mode(data_right_skewed)
skewness_right = skew(data_right_skewed)

# Plotting
plt.figure(figsize=(8,3))

plt.subplot(1, 2, 1)
sns.histplot(data_right_skewed, bins=30, kde=True, color='skyblue')
plt.title(f'Right-Skewed Histogram (Skew: {skewness_right:.2f})')
plt.axvline(mean_right, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_right:.2f}')
plt.axvline(median_right, color='green', linestyle='dashed', linewidth=1, label=f'Median: {median_right:.2f}')
plt.axvline(mode_right, color='black', linestyle='dashed', linewidth=1, label=f'Mode: {mode_right:.2f}')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.legend()

# --- 2. Left-Skewed Data (Negative Skew) ---
# Generate left-skewed data (e.g., test scores, if most people score high)
# A common technique is to subtract right-skewed data from a constant
data_left_skewed = 100 - np.random.exponential(scale=2, size=1000) * 10
# Ensure no values exceed a reasonable upper bound for this example
data_left_skewed = np.clip(data_left_skewed, 0, 100)

# Calculate statistics
mean_left = np.mean(data_left_skewed)
median_left = np.median(data_left_skewed)
mode_left = stats.mode(data_left_skewed)
skewness_left = skew(data_left_skewed)

# Plotting
plt.subplot(1, 2, 2)
sns.histplot(data_left_skewed, bins=30, kde=True, color='salmon')
plt.title(f'Left-Skewed Histogram (Skew: {skewness_left:.2f})')
plt.axvline(mean_left, color='red', linestyle='dashed', linewidth=1, label=f'Mean: {mean_left:.2f}')
plt.axvline(median_left, color='green', linestyle='dashed', linewidth=1, label=f'Median: {median_left:.2f}')
plt.axvline(mode_left, color='black', linestyle='dashed', linewidth=1, label=f'Mode: {mode_left:.2f}')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.legend()


plt.tight_layout()
plt.show()

# Print statistics for clarity
print('\n')
print(f"--- Right Skew Statistics ---")
print(f"Mean: {mean_right:.2f}")
print(f"Median: {median_right:.2f}")
print(f"Skewness: {skewness_right:.2f} (Positive value indicates right skew)")

print(f"\n--- Left Skew Statistics ---")
print(f"Mean: {mean_left:.2f}")
print(f"Median: {median_left:.2f}")
print(f"Mode: {mode_left:.2f}")
print(f"Skewness: {skewness_left:.2f} (Negative value indicates left skew)")